### ISSUE TITLE
Starting notifications on EEG data using bleak or pygatt

### ISSUE THREAD

**Issue by sunshineinsandiego** [xloem/muse-lsl#18]
Hi - I am trying to subscribe to the EEG characteristics using `bleak` or `pygatt` as I need to stream EEG data into a non-LSL application, and this seemed like the right group to ask for advice given @xloem wrote about implementing the `bleak` backend here: https://github.com/alexandrebarachant/muse-lsl/pull/148. 

`bleak` test program:
```
import sys
import os
import asyncio


from bleak import BleakClient


ADDRESS = '28686572-5A71-435E-952A-6F4292F5B04A'
CHARACTERISTIC_UUID = '273e0003-4c4d-454d-96be-f03bac821358'

if len(sys.argv) == 3:
    ADDRESS = sys.argv[1]
    CHARACTERISTIC_UUID = sys.argv[2]


def notification_handler(sender, data):
    """Simple notification handler which prints the data received."""
    print("{0}: {1}".format(sender, data))


async def run(address):

    async with BleakClient(address) as client:

        await client.connect()
        print("Is connected")

        # start notifications on control characteristic
        await client.start_notify('273e0001-4c4d-454d-96be-f03bac821358', notification_handler)
        # write to control handle, set preset to 21
        await client.write_gatt_char('273e0001-4c4d-454d-96be-f03bac821358', bytearray([0x04, 0x70, 0x32, 0x31, 0x0a]), False)
        # write to control handle get device info
        await client.write_gatt_char('273e0001-4c4d-454d-96be-f03bac821358', bytearray([0x03, 0x76, 0x31, 0x0a]), False)
        # write to control handle for resume
        await client.write_gatt_char('273e0001-4c4d-454d-96be-f03bac821358', bytearray([0x02, 0x64, 0x0a]), False)
        # start notifications on TP9
        await client.start_notify('273e0003-4c4d-454d-96be-f03bac821358', notification_handler)
        #await client.stop_notify(CHARACTERISTIC_UUID)


if __name__ == "__main__":

    os.environ["PYTHONASYNCIODEBUG"] = str(1)
    loop = asyncio.get_event_loop()
    loop.run_until_complete(run(ADDRESS))
```

Output:
```
% python3 bleaktest.py     
Is connected
13: bytearray(b'\x08{"rc":0}\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
13: bytearray(b'\x10{"ap":"headset",\x00\x00\x00')
13: bytearray(b'\x13"sp":"Blackcomb_rev')
13: bytearray(b'\x03B",":"Blackcomb_rev')
13: bytearray(b'\x10"tp":"consumer",rev')
13: bytearray(b'\x0c"hw":"10.6",er",rev')
13: bytearray(b'\x07"bn":2,0.6",er",rev')
13: bytearray(b'\x0e"fw":"1.0.21",",rev')
13: bytearray(b'\r"bl":"1.0.0",,",rev')
13: bytearray(b'\x07"pv":1,.0.0",,",rev')
13: bytearray(b'\x07"rc":0}.0.0",,",rev')
```

`pygatt` test program:
```
import pygatt
import time
from binascii import hexlify

adapter = pygatt.BGAPIBackend()
#adapter = pygatt.GATTToolBackend('hci0') linux backend

def handle_data(handle, raw_value):
    """
    handle -- integer, characteristic read handle the data was received on
    raw_value -- bytearray, the data returned in the notification
    """

    value = hexlify(raw_value)
    print(value)

try:
    adapter.start()
    device = adapter.connect('00:55:DA:B7:98:9C')
    print("Is connected")

    # subscribe to control characteristic
    device.subscribe('273e0001-4c4d-454d-96be-f03bac821358', callback = handle_data)
    #ask for device info
    device.char_write_handle(0x000e, bytearray([0x03, 0x76, 0x31, 0x0a]), wait_for_response = True)
    # subscribe to eeg characteristic
    device.subscribe('273e0006-4c4d-454d-96be-f03bac821358', callback = handle_data, wait_for_response =  True)
finally:
    adapter.stop()
```

Output:
```
% python3 pygatttest.py
Is connected
```
As you can see from the output, I'm able to connect briefly to the Muse 2 headset, but the connection is immediately dropped with both `bleak` and `pygatt`. I know that the connection is working because 
(a) the indicator light on the Muse goes from blinking to steady, and 
(b) I get feedback from the Muse after writing to the command characteristic. 
But after writing and receiving that initial notification, the connection immediately drops. (which may be similar to what @daniele is reporting here: https://github.com/xloem/muse-lsl/issues/17)

I think this may be due to the fact that I'm not writing a specific control sequence to the control UUID, but I can't seem to find the correct sequence in the code base. It appears that it might be 'd' or 'k'?

From `muse.py`:
```
    def resume(self):
        """Resume streaming, sending 'd' command"""
        self._write_cmd_str('d')

    def keep_alive(self):
        """Keep streaming, sending 'k' command"""
        self._write_cmd_str('k')
```

Any advice would be appreciated!

Thanks much.

**Comment by xloem** [comment]
Hey,

Your program is ending when your function reaches the end.  You need to add a delay in or something.

You can also import muse-lsl's parts and use them without using the lsl functionality.  Then if you find things to fix or improve you can share what you change with the community.

**Comment by sunshineinsandiego** [comment]
Ah yes, perfect. That worked with the bleak backend. No need for control inputs! Simply added a line to the end of the run loop:

```
await aioconsole.ainput('Running: Press a key to quit')
```

Thanks for the help! And yes, I will try to replicate using `muse-lsl` pieces and will let you know how that goes.

**Comment by xloem** [comment]
here's where muse-lsl does it: https://github.com/alexandrebarachant/muse-lsl/blob/20f7fac07d89f727c198795ca378f3d539cbb016/muselsl/stream.py#L233

muse.py has most of the functions compartmentalized away from lsl but is missing a small handful of advanced functions
